version: "2"
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    hostname: filebrowser
    restart: unless-stopped
    volumes:
      - /:/host
    networks:
      vlan:
        ipv4_address: "${IP:-172.19.0.1}"                         # 修改不同的IP【*】
networks:
  vlan:
    external: true
