version: "3.8"
services:
  ghcr:
    image: registry:2.8.2
    volumes:
      - /root/config.yml:/etc/docker/registry/config.yml
      - /etc/localtime:/etc/localtime
      - /var/lib/registry:/var/lib/registry
    # ports:
    #   - 5000:5000

    #  - REGISTRY_TRACING_ENABLED=false 高于3.0版本采用
    restart: always
    networks:
       vlan:
         ipv4_address: "${IP:-172.19.0.2}"                         # 修改不同的IP【*】
networks:
  vlan:
    external: true
