version: '2'
services:
 socks5:
    image: "lihaixin/gost:s5-2.11.5"
    restart: unless-stopped                             # unless-stopped  always          
    environment:
      NO: ""
    volumes:
      - gostfile:/home
    networks:
      vlan:
        ipv4_address: "${IP:-172.19.0.1}"                                                                                        # 修改不同的IP【*】
networks:
  vlan:
    external: true

volumes:
  gostfile:
