version: '2'
services:
  android:
    image: budtmo/docker-android:emulator_11.0                                          # https://github.com/budtmo/docker-android
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    restart: on-failure
    environment:
      MULATOR_DEVICE: "Samsung Galaxy S10"                                               # 系统标识
      WEB_VNC: true
      
    volumes:
      - android:/storage
      
    networks:
      vlan:
        ipv4_address: "${IP:-192.168.2.13}"                                              # 修改不同的IP【*】
networks:
  vlan:
    external: true
    
volumes:
  android:
