version: "3.8"
services:
  openresty-manager:
     image: lihaixin/dockerfile:2.0
                                                                   # network_mode: "host"
     restart: always
     networks:
       vlan:
         ipv4_address: "${IP:-172.19.0.1}"                         # 修改不同的IP【*】
networks:
  vlan:
    external: true    
