services:
  h-ui:
    image: lihaixin/h-ui
    privileged: true
    container_name: h-ui
    restart: always
    network_mode: host
    volumes:
      - h-ui:/h-ui
    environment:
      TZ: Asia/Shanghai
      WEBPORT: ${WEBPORT:-8083}
      PORT: ${PORT:-446}
      MPORT: ${MPORT:-25000:26000}
      
volumes:
  h-ui:
