services:
  h-ui:
    image: jonssonyan/h-ui
    cap_add:
      - NET_ADMIN
    container_name: h-ui
    restart: always
    network_mode: host
    volumes:
      - h-ui:/h-ui
    environment:
      TZ: Asia/Shanghai
      
volumes:
  h-ui:
