services:
  h-ui:
    image: jonssonyan/h-ui
    privileged: true
    container_name: h-ui
    restart: always
    network_mode: host
    volumes:
      - h-ui:/h-ui
    environment:
      TZ: Asia/Shanghai
    command: ["./h-ui", "-p", "${PORT:-8082}"]
      
volumes:
  h-ui:
