services:
  h-ui:
    image: lihaixin/h-ui
    privileged: true
    container_name: h-ui
    hostname: h-ui
    restart: always
    network_mode: host
    volumes:
      - h-ui:/h-ui
      - /etc/cert:/etc/cert
    environment:
      TZ: Asia/Shanghai
      WEBPORT: ${WEBPORT:-8081}
      
volumes:
  h-ui:
