version: "2"
services:
  portainer_agent:
    image: portainer:agent-2.19.5 
    container_name: ui2
    hostname: ui2
    restart: unless-stopped
    privileged: true
    environment:
      EDGE: "1"
      EDGE_ID: 733c7ebf-6804-4604-ae41-a1444b6cec34
      EDGE_KEY: aHR0cHM6Ly91aS0yLjE1MDk5Lm5ldHx1aS0yLjE1MDk5Lm5ldDo4MDA4fDROaFAzd2lsOENIbkFLYzl6Mi9DUndGQkhJWGF1LzRlZnhpbVdzWlhBNXc9fDQ5NA
      EDGE_INSECURE_POLL: "1"
    ports:
      - "9001:9001"
    volumes:
      - portainer_agent_data:/data                                               # 永久存放portainer数据位置
      - /var/run/docker.sock:/var/run/docker.sock                                # docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes                          # 卷管理
      - /:/host                                                                  # 文件管理
    networks:
      vlan:
        ipv4_address: 192.168.2.11                                               # 修改不同的IP【*】
volumes:
  portainer_agent_data:
networks:
  vlan:
    external: true
