version: "2"
services:
  portainer_agent:
    image: lihaixin/portainer:agent-2.19.5 
    container_name: ui2
    hostname: portainer_agent
    restart: unless-stopped
    privileged: true
    environment:
      EDGE: "${EDGE}"
      EDGE_ID: "${EDGEID:-f63326d6-1844-45c1-9f55-1a0dc63b6590}"
      EDGE_KEY: "${EDGEKEY:-aHR0cHM6Ly91aS0yLjE1MDk5Lm5ldHx1aS0yLjE1MDk5Lm5ldDoyMXw0TmhQM3dpbDhDSG5BS2M5ejIvQ1J3RkJISVhhdS80ZWZ4aW1Xc1pYQTV3PXw1MDU}"
      EDGE_INSECURE_POLL: "1"
    ports:
      - "9001:9001"
      - "9090:9090"
    volumes:
      - /var/portainer_agent_data:/data                                          # 永久存放portainer数据位置
      - /var/run/docker.sock:/var/run/docker.sock                                # docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes                          # 卷管理
      - /:/host                                                                  # 文件管理
