version: "3.7"
services:
  github:
    image: hunsh/gh-proxy-py:latest
    container_name: gh
    hostname: gh
    restart: unless-stopped
    # network_mode: "bridge"
    logging:
      driver: json-file
      options:
        max-size: 1m
    # ports:
    #  - "83:80"
    networks:
      vlan:
        ipv4_address: "${IP:-172.19.0.1}"                                                                                        # 修改不同的IP【*】
networks:
  vlan:
    external: true
