version: "3.7"
services:

  vnstat:
    image: lihaixin/vnstat:latest
    container_name: vnstat
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - vnstatdb:/var/lib/vnstat
    environment:
      - HTTP_PORT=0                             #http服务器端口,或者调整8685，用于0禁用http服务器
      - HTTP_BIND=*                             #用于绑定http服务器的IP地址，用于127.0.0.1仅绑定到本地主机并防止远程访问
      - HTTP_LOG=/dev/stdout                    #Http服务器日志输出文件，/dev/stdout用于输出到控制台和/dev/null禁用日志记录
      - LARGE_FONTS=0                           #在图像中使用大字体（0：否，1：是）
      - CACHE_TIME=1                            #在给定的分钟数内缓存创建的图像（0：禁用）
      - RATE_UNIT=1                             #使用的流量速率单位，0：字节，1：比特
      - PAGE_REFRESH=0                          #页面自动刷新间隔以秒为单位（0：禁用）
      - MAXTX=950                               #最大传出流量,默认为G
      - MAXALL=1000                             #进出双向最大流量.默认为G
      - MAXLIMTYPE=GiB                          #流量统计单位

volumes:
  vnstatdb:
