version: '2'
services:
  xray:
    image: "lihaixin/xray:one-1.7.5"
    restart: always
    ports:
      - "443:443"
      - "80:80"
    environment:
      DOMAIN: "youdomain.com"
      HOSTNAME: "hk8"
      PASSWORD: "888888"
      PORT: "443"
      USERNAME: "000S5"
      PASSWORD: "000S5"
      S5PORT: 9001
      BACKURL: "127.0.0.1:88"
    volumes:
      - xrayfile:/etc/nginx
      - /etc/cert:/etc/cert
volumes:
  xrayfile:
