version: '2'
services:
  armbian:
    image: qemux/qemu-docker              # https://github.com/qemus/qemu-docker
    container_name: armbian
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    restart: on-failure
    environment:
      # ARGUMENTS: "-netdev user,id=hostnet1 -device virtio-net-pci,romfile=,netdev=hostnet1,id=net1"
      BOOT: "https://dl.armbian.com/uefi-x86/archive/Armbian_24.8.1_Uefi-x86_jammy_current_6.6.47.img.qcow2.xz"
      DISK_SIZE: "${DISK_S:-10G}"
      RAM_SIZE: "${MEM_S:-2G}"
      DISK_FMT: "${DISK_F:-qcow2}"
      
    volumes:
      - armbian:/storage
      - ${BOOT_PATH:-/var/armbian/armbian.img}:/boot
      
    networks:
      vlan:
        ipv4_address: "${IP:-192.168.2.13}"                                              # 修改不同的IP【*】
networks:
  vlan:
    external: true

volumes:
  armbian:
