version: "2"
services:
  x-ui:
    image: lihaixin/x-ui:0.3.4
    container_name: x-ui
    hostname: x-ui
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    volumes:
      - /etc/x-ui:/etc/x-ui
      - /etc/cert:/etc/cert
    environment:
      - DOMAIN=15099.net                                            # 你的域名
      - HOSTNAME=hk10                                               # 你的主机名
      - WEBPORT=54321                                               # 管理地址端口
      - PASSWD=password                                             # 管理密码
