version: "2"
services:
  toolbox:
    image: lihaixin/toolbox
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    stdin_open: true                      # -i interactive
    tty: true                             # -t tty
    pid: "host"
    volumes:
      - /root/.ssh/id_rsa:/root/.ssh/id_rsa
      - /var/run/docker.sock:/var/run/docker.sock
