version: '3.7'
volumes:
  softether:
  softether-logs:
  
services:
  vpn:
    image: "lihaixin/softether:server.alpine.20220911"
    restart: always
    network_mode: host
    privileged: true
    environment:
      DOMAIN: ${DOMAIN}
      HOST: ${HOST}
      MTU: ${MTU}
      MainINF: ${MainINF}                    #默认为空,让程序自动检查,如果是走openvpn出去,设置为tun+ 
      OPENVPN_PORT: ${OPENVPN_PORT}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      PSK: ${PSK}
      SPW: ${SPW}
      MaxUpload: ${MaxUpload}
      MaxDownload: ${MaxDownload}
      MultiLogins: ${MultiLogins}
      SSTP: ${SSTP}
      OPENVPN: ${OPENVPN}
      L2TP: ${L2TP}
      DNS: ${DNS}
    volumes:
      - /etc/cert:/etc/cert
      - softether:/usr/vpnserver
      - softether-logs:/var/log/vpnserver
