version: '2'
services:
  vpn:
    image: "lihaixin/softether"
    restart: always
    network_mode: host
    privileged: true
    environment:
      MTU: "1300"
      INTERFACE: "ens3"
      USERNAME: "test"
      PASSWORD: "test"
    volumes:
      - server:/usr/local/vpnserver
volumes:
  server:
