version: '2'
services:
  vpn:
    image: "lihaixin/softether"
    restart: always
    network_mode: host
    privileged: true
    environment:
      MTU: ${MTU}
      INTERFACE: ${INTERFACE}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    volumes:
      - server:/usr/local/vpnserver
volumes:
  server:
