version: '2'
services:
  vpn:
    image: "lihaixin/softether:server.alpine"
    restart: always
    network_mode: host
    privileged: true
    environment:
      MTU: "1300"
    volumes:
      - server:/usr/local/vpnserver
volumes:
  server:
