version: '2'
services:
  client:
    image: "lihaixin/softether:client"
    container_name: vpngate1
    ports:
      - "9930:9930"
    restart: always
    privileged: true
    network_mode: "bridge"
    environment:
      VPN_SERVER: vpn425286490.opengw.net
      VPN_PORT: 1361
      VIRTUAL_HUB: WINGATE
      ACCOUNT_USER: vpn
      ACCOUNT_PASS: vpn
      TAP_IPADDR: dhcp 
  server:
    image: "lihaixin/softether"
    restart: always
    network_mode: "container:vpngate1"
    privileged: true
    depends_on:
      - client
    environment:
      MTU: 1200
