version: '3'
services:
  vpnserver:
    image: "lihaixin/softether"
    restart: always
    network_mode: "container:vpngate"                  # 调整和容器vpngate使用同一IP地址,container:iptables
    privileged: true
    depends_on:
      - vpngate
    environment:
      MTU: 1200
      
  vpngate:
    image: "lihaixin/softether:client"
    restart: always
    privileged: true
    networks:
      my-network:
        ipv4_address: 10.20.1.11          #修改IP *  
    environment:
      VPN_SERVER: vpn287448755.opengw.net #支持域名和IP *
      VPN_PORT: 995                       #修改端口 *
      VIRTUAL_HUB: VPNGATE
      ACCOUNT_USER: vpn
      ACCOUNT_PASS: vpn
      TAP_IPADDR: dhcp
     
networks:
  my-network:
    name: vpngate-vpn-network
    ipam:
     config:
       - subnet: 10.20.0.0/16
         gateway: 10.20.0.1
