version: '3'
# 使用自定义网络,记得在母机开机启动添加  iptables -t nat -I POSTROUTING -p tcp -d 172.19.0.0/16 --dport 1080 -j SNAT --to-source 172.19.0.1
services:
  vpngate:
    image: "lihaixin/softether:client"
    ports:
      - "10801:1080" # 开启socks5端口映射
    restart: always
    privileged: true
    #network_mode: "bridge"  # 使用桥接网络
    networks:
      - my-network
    environment:
      VPN_SERVER: 211.48.118.80
      VPN_PORT: 995
      VIRTUAL_HUB: VPNGATE
      ACCOUNT_USER: vpn
      ACCOUNT_PASS: vpn
      TAP_IPADDR: dhcp
  socks5:
    image: "lihaixin/gost:s5"
    restart: always
    #network_mode: "bridge" # 启动后通过portainer调整和vpngate一个容器网络
    networks:
      - my-network
    privileged: true
    depends_on:
      - vpngate
    environment:
      USER: a1
      PASSWD: a1
      PORT: 1080
      
networks:
  my-network:
    name: vpngate-s5-network
