version: '3'
services:
  vpngate:
    image: "lihaixin/softether:client"
    # ports:
    #   - "9930:9930" # 开启远程客户端链接端口
    restart: always
    privileged: true
    # network_mode: "bridge"  # 使用桥接网络
    networks:
      - my-network
    environment:
      VPN_SERVER: vpn287448755.opengw.net #支持域名和IP *
      VPN_PORT: 995                      #修改端口 *
      VIRTUAL_HUB: VPNGATE
      ACCOUNT_USER: vpn
      ACCOUNT_PASS: vpn
      TAP_IPADDR: dhcp
  vpnserver:
    image: "lihaixin/softether"
    restart: always
    # network_mode: "container:vpngate1" # 调整和容器vpngate使用同一IP地址
    networks:
      - my-network
    privileged: true
    depends_on:
      - vpngate
    environment:
      MTU: 1200
      
networks:
  my-network:
    name: vpngate-vpn-network
    ipam:
     config:
       - subnet: 172.20.0.0/16
         gateway: 172.20.0.1/16
         aux_addresses:
          vpngate: 172.20.1.1/16
          vpnserver: 172.20.2.1/16
