version: '2'
services:
  vpngate:
    image: "lihaixin/softether:client"
    # ports:
    #   - "9930:9930" # 开启远程客户端链接端口
    restart: always
    privileged: true
    # network_mode: "bridge"  # 使用桥接网络
    networks:
      - my-network
    environment:
      VPN_SERVER: vpn425286490.opengw.net
      VPN_PORT: 1361
      VIRTUAL_HUB: VPNGATE
      ACCOUNT_USER: vpn
      ACCOUNT_PASS: vpn
      TAP_IPADDR: dhcp 
  vpnserver:
    image: "lihaixin/softether"
    restart: always
    # network_mode: "container:vpngate1" # 调整和容器vpngate使用同一IP地址
    networks:
      - my-network
    privileged: true
    depends_on:
      - vpngate
    environment:
      MTU: 1200
      
networks:
  my-network:
    name: vpngate-s5-network
