version: "2"
services:
  toolbox:
    image: lihaixin/toolbox:debian
    restart: unless-stopped
    privileged: true
    stdin_open: true                      # -i interactive
    tty: true                             # -t tty
    networks:
      vlan:
        ipv4_address: "${IP:-172.19.0.201}"                                                                                        # 修改不同的IP【*】
networks:
  vlan:
    external: true
