version: '3.3'
services:
  next-terminal:
    image: "dushixiang/next-terminal:0.3.4"
    restart: always
    ports:
      - "8088:8088"
    volumes:
      - /root/next-terminal/drive:/usr/local/next-terminal/drive
      - /root/next-terminal/recording:/usr/local/next-terminal/recording
      - /root/next-terminal/next-terminal.db:/usr/local/next-terminal/next-terminal.db
