version: '3.3'
services:
  xray:
    image: "lihaixin/xray:1.4.0"
    restart: always
    ports:
      - "443:443"
      - "80:80"
    environment:
      DOMAIN: "xray.youdomain.com"
      PASSWORD: "888888"
      ID: "a677a91f-f458-4627-ae9d-e3f28807af51"
      BACKURL: "127.0.0.1:80"
    volumes:
      - xray_cert:/etc/xray/cert
