version: '3.3'
services:
  next-terminal:
    image: "dushixiang/next-terminal:0.3.4"
    restart: always
    ports:
      - "8088:8088"
    volumes:
      - /root/next-terminal/drive:/usr/local/next-terminal/drive
      - /root/next-terminal/recording:/usr/local/next-terminal/recording
  
  xray:
    image: "lihaixin/xray:1.4.0"
    restart: always
    ports:
      - "443:443"
      - "80:80"
    environment:
      DOMAIN: "xray.youdomain.com"
      PASSWORD: "888888"
      ID: "a677a91f-f458-4627-ae9d-e3f28807af51"
      BACKURL: "172.17.0.1:8088"
    volumes:
      - /root/xray/cert:/etc/xray/cert
