version: '2'
services:
  ikuai:
    image: qemux/qemu                                  # https://github.com/qemus/qemu
    # container_name: ikuai
    devices:
      - /dev/kvm
      - /dev/vhost-net
      - /dev/net/tun
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    restart: on-failure
    environment:
      ARGUMENTS: "-netdev user,id=hostnet1 -device virtio-net-pci,romfile=,netdev=hostnet1,id=net1"
      BOOT: "https://patch.ikuai8.com/3.x/iso/iKuai8_x32_3.6.13_Build202301131532.iso"
      DISK_SIZE: "${DISK_S:-10G}"
      RAM_SIZE: "${MEM_S:-2G}"
      DISK_FMT: "${DISK_F:-qcow2}"
      DHCP: "Y"
      
    volumes:
      - ikuai:/storage
      
    networks:
      vlan:
        ipv4_address: "${IP:-172.19.0.1}"                                             # 修改不同的IP【*】

networks:
  vlan:
    external: true

volumes:
  ikuai:
