 {
			"type": 3,
			"title": "ikuai",
			"description": "一键安装企业级路由器IKUAI",
			"note": "通过docker容器，配合macvlan,快速部署ikuai软路由.",
			"categories": ["OS"],
			"platform": "linux",
			"logo": "https://dockerfile.15099.net/logo/dsm.png",
			"repository": {
				"url": "https://github.com/lihaixin/dockerfile",
				"stackfile": "stacks/dsm/docker-compose.yml"
			}
		}
,
