version: '2'
services:
  ikuai:
    image: qemux/qemu-docker
    container_name: ikuai
    devices:
      - /dev/kvm
      - /dev/vhost-net
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    restart: on-failure
    environment:
      ARGUMENTS: "-netdev user,id=hostnet1 -device virtio-net-pci,romfile=,netdev=hostnet1,id=net1"
      BOOT: "https://patch.ikuai8.com/3.x/iso/iKuai8_x64_3.7.13_Build202406212115.iso"
      DISK_SIZE: "4G"
      RAM_SIZE: "4G"
      WEB_VNC: true
      DHCP: "Y"
      
    volumes:
      - /var/ikuai:/storage
    networks:
      wan1:

      
networks:
  wan1:
    name: 1macvlan
    driver: macvlan
    driver_opts:
      parent: vmbr0                                  # 对接虚拟机网卡名称，爱快内置的debian12虚拟机第一个网卡默认 ens3
    ipam:
      config:
        - subnet: 192.168.2.0/24                    # 局域网网段范围
          gateway: 192.168.2.254                     # 局域网网关
