services:
  acme:
    image: lihaixin/acme
    container_name: acme
    hostname: acme
    ports:
      - "80:80"
    volumes:
      - etc_cert:/etc/cert
    environment:
      TYPE: zerossl # 可选值：zerossl 或 letsencrypt
      DNS: dns_cf # 可选值：dns_cf, dns_namecom, dns_gd, dns_namesilo, dns_dp, dns_ali
      DOMAIN: youdomain.com
      ID: info@domain.com
      KEY: 558ef6820cea14627f986548c96fcb6cb××××
volumes:
  etc_cert:
