version: '2'
services:
  dsm:
    container_name: dsm
    image: vdsm/virtual-dsm
    environment:
      DISK_SIZE: "32G"
      DISK_FMT: "qcow2"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/dsm:/storage
    stop_grace_period: 2m

    networks:
      wan1:
        ipv4_address: 172.19.0.15                     #  *修改不同的IP
networks:
  wan1:
    name: 1macvlan
    driver: macvlan
    driver_opts:
      parent: vmbr0                                  # 对接虚拟机网卡名称
    ipam:
      config:
        - subnet: 172.19.0.0/16                     # 局域网网段范围
          gateway: 172.19.0.254                     # 局域网网关
