version: '2'
services:
  istoreos:
    image: qemux/qemu-docker                      # https://github.com/qemus/qemu-docker
    container_name: ikuai
    devices:
      - /dev/kvm
      - /dev/vhost-net
      - /dev/net/tun
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    restart: on-failure
    environment:
      ARGUMENTS: "-netdev user,id=hostnet1 -device virtio-net-pci,romfile=,netdev=hostnet1,id=net1"
      BOOT: "https://dl.istoreos.com/iStoreOS/x86_64_efi/istoreos-22.03.7-2024080210-x86-64-squashfs-combined-efi.img.gz"
      DISK_SIZE: "4G"
      RAM_SIZE: "4G"
      WEB_VNC: true
      DHCP: "Y"
      
    volumes:
      - /var/istoreos:/storage
    networks:
      vlan:
        ipv4_address: "${IP:-172.19.0.1}"                                                                                        # 修改不同的IP【*】
networks:
  vlan:
    external: true
