version: '2'
services:
 lumi:
    image: "luminati/luminati-proxy"         # https://github.com/luminati-io/luminati-proxy
    restart: unless-stopped                  # unless-stopped  always          
    environment:
      PORT: 24000
      WEBPORT: 22999
    ports:
      - "22999:22999"                        # 新增这一行，将容器的22999端口映射到宿主机的22999端口
    command: proxy-manager
    volumes:
      - lpm-root:/root
    networks:
      my-network:
        ipv4_address: 10.22.1.11
 networks:
  my-network:
    name: lumi-proxy-network
    ipam:
      config:
        - subnet: 10.22.1.0/24
          gateway: 10.22.1.254
volumes:
  lpm-root:
