version: '2'
services:
  guacd:
    image: dushixiang/guacd:1.3.0
    volumes:
      - data:/usr/local/next-terminal/data
    restart:
          always
  next-terminal:
    image: dushixiang/next-terminal:1.0.0
    environment:
      DB: sqlite
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
    ports:
      - "8088:8088"
    volumes:
      - /etc/machine-id:/etc/machine-id
      - /etc/localtime:/etc/localtime
      - data:/usr/local/next-terminal/data
      - drive:/usr/local/next-terminal/drive
      - recording:/usr/local/next-terminal/recording
    restart:
          always
volumes:
  data:
  drive:
  recording:
