version: '2'
services:
  macos:
    image: dockurr/macos                                   # https://github.com/dockur/macos
    container_name: macos
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    restart: on-failure
    environment:
      VERSION: "ventura"                                   # 系统标识  支持 sonoma ventura monterey big-sur
      
    volumes:
      - /var/macos:/storage
    networks:
      wan1:
        ipv4_address: 172.19.0.1                         # 修改不同的IP *
      
networks:
  wan1:
    name: 1macvlan
    driver: macvlan
    driver_opts:
      parent: eth0                                  # 对接宿主机网卡名称 
    ipam:
      config:
        - subnet: 172.19.0.0/16                    # 局域网网段范围
          gateway: 172.19.0..254                     # 局域网网关
