version: '2'
services:
  macos:
    image: dockurr/macos                                   # https://github.com/dockur/macos
    container_name: macos15
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    restart: on-failure
    environment:
      VERSION: "15"                                       # 系统标识  支持 sonoma ventura monterey big-sur
    volumes:
      - macos15:/storage
    networks:
      wan1:
        ipv4_address: "${IP:-172.19.0.1}"               # 修改不同的IP【*】  WEBVNC地址： http://<ip>:8006  RDP地址：<ip>:3389
      
networks:
  vlan:
    external: true
volumes:
  macos15:
