version: '2'
services:
  macos:
    image: dockurr/macos                                   # https://github.com/dockur/macos
    # container_name: macos
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-net
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    restart: on-failure
    environment:
      VERSION: "15"                                       # 系统标识  支持 sonoma ventura monterey big-sur
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DHCP: "Y"
    volumes:
      - macos:/storage
      - /root:/shared
    networks:
      vlan:
        ipv4_address: "${IP:-192.168.2.196}"               # 修改不同的IP【*】  WEBVNC地址： http://<ip>:8006  RDP地址：<ip>:3389
      
networks:
  vlan:
    external: true
volumes:
  macos:
