version: '2'
services:                                                           # https://github.com/okxlin/docker-1panel 默认端口：10086 默认账户：1panel 默认密码：1panel_password 后台路径：entrance
  1panel:
    container_name: 1panel                                          # 容器名
    image: moelin/1panel:latest
    restart: always
    pid: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /opt:/opt                                                   # 文件存储映射
      - /root:/root                                                 # 可选的文件存储映射
    environment:
      - TZ=Asia/Shanghai                                            # 时区设置
    networks:
      vlan:
        ipv4_address: "${IP:-172.19.0.1}"                           # 修改不同的IP【*】
networks:
  vlan:
    external: true
