version: "2"
services:
  portainer:
    image: lihaixin/ui:ce-2.24.1                # https://hub.docker.com/r/lihaixin/portainer
    container_name: ui
    hostname: portainer
    restart: unless-stopped
    network_mode: "bridge"                             # bridge 网络
    environment:
      PASSWORD: "${PASSWORD:-@china1234567}"           # 密码不能低于12位，留空为启动后再自己创建
      COUNTRY: "cn"                                    # cn显示中文，en显示英文
      TPORT: "8000"                                    # client端连接的隧道端口
    ports:
      - "9443:9443"                                    # 网页管理界面端口
      - "8000:8000"                                    # 隧道端口
    volumes:
      - /var/portainer_data:/data                      # 永久存放portainer数据位置
      - /var/run/docker.sock:/var/run/docker.sock      # docker.sock

