version: '3.7'
services:
 openvpn1:
    image: "lihaixin/openvpn"
    restart: unless-stopped
    privileged: true 
    environment:
      - TYPE=vyprvpn
      - PROTO=udp
      - ADDR=ar1.vyprvpn.com
      - PORT=443
      - USER=user
      - PASSWD=passwd
      - SOCKS5=1
      - SUSER=a1
      - SPASSWD=a1
      - HTTP_PORT=80
      - MAXNUM=50
    networks:
      my-network:
        ipv4_address: 10.21.1.11
        
networks:
  my-network:
    name: openvpn-S5-vpn-network
    ipam:
      config:
        - subnet: 10.21.0.0/16
          gateway: 10.21.0.1
