version: '3.7'
services:
 softether:
    image: "lihaixin/softether:server.alpine"
    restart: unless-stopped                      # unless-stopped  always
    network_mode: "service:openvpn1"             #"bridge" "host"  "none" "service:[service name]"  "container:[container name/id]"
    privileged: true
    depends_on:
      - openvpn1    
    environment:
      - DOMAIN=15099.net
      - HOST=kr2
      - MainINF=tun+                             #默认为空,让程序自动检查,如果是走openvpn出去,设置为tun+     
      - USERNAME=test
      - PASSWORD=test
      - PSK=vpnvpn88
      - SPW=softether
      - MaxUpload=5000000
      - MaxDownload=5000000
      - MultiLogins=3
      - MTU=1200
      - SSTP=0
      - OPENVPN=0
      - L2TP=0
      - OPENVPN_PORT=11194
      - DNS="8.8.8.8,1.1.1.1"
      
 openvpn1:
    image: "lihaixin/openvpn"
    restart: unless-stopped
    privileged: true 
    environment:
      - TYPE=vyprvpn
      - PROTO=udp
      - ADDR=ar1.vyprvpn.com
      - PORT=443
      - USER=user
      - PASSWD=passwd
      - SOCKS5=1
      - SUSER=a1
      - SPASSWD=a1
      - HTTP_PORT=80
      - MAXNUM=50
    networks:
      my-network:
        ipv4_address: 10.21.1.11
        
networks:
  my-network:
    name: openvpn-S5-vpn-network
    ipam:
      config:
        - subnet: 10.21.0.0/16
          gateway: 10.21.0.1
