version: '2'
services:
 openvpn1:                                     # 服务名称
    image: "lihaixin/openvpn"
    restart: unless-stopped
    privileged: true 
    environment:
      - TYPE=vpngate
      - PROTO=udp
      - ADDR=***.vpngate.net
      - PORT=443
      - USER=user
      - PASSWD=passwd
      - SOCKS5=1
      - SUSER=a1
      - SPASSWD=a1
      - HTTP_PORT=0                              # 设置为0,关闭网页
      - MAXNUM=50
      - MAXRATE=4mbit
    networks:
      my-network:
        ipv4_address: 10.21.1.11
        
networks:
  my-network:
    name: openvpn-S5-vpn-network-1
    ipam:
      config:
        - subnet: 10.21.1.0/24
          gateway: 10.21.1.1
