services:
  windows:
    image: dockurr/windows
    container_name: win7
    environment:
      VERSION: "win7"                                                   # 系统标识
      RAM_SIZE: "1G"                                                      # 分配的内存
      CPU_CORES: "2"                                                      # 分配的核心
      DISK_SIZE: "10G"                                                    # 分配储存空间
      LANGUAGE: "Chinese"
      ARGUMENTS: "-device usb-host,vendorid=0x232b,productid=0x0f13"      # 调整和上面lsusb输出一致，加0x表示为十六进制
    devices:
      - /dev/kvm
      - /dev/bus/usb                                                      # 调用usb到容器
    cap_add:
      - NET_ADMIN
    ports:
      - 8007:8006                                                         # 和飞牛相册端口冲突
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - win7:/storage
     # - /vol2/1000/os/winxp.iso:/custom.iso
volumes:
  win7:
