name: Manual Docker Build
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g. v1.0.0)'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME_LIHAIXIN }}
        password: ${{ secrets.DOCKER_PASSWORD_LIHAIXIN }}

    - name: Build and push multi-platform images
      id: build-and-push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME_LIHAIXIN }}/${{ github.event.repository.name }}:${{ github.event.inputs.tag }}
          ${{ secrets.DOCKER_USERNAME_LIHAIXIN }}/${{ github.event.repository.name }}:latest
