name: Update Descripion
on:
  push:
    branches:
      - master
    paths:
      - readme.md
      - README.md
      - .github/workflows/hub_readme.yml

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - 
      name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME_LIHAIXIN }}
        password: ${{ secrets.DOCKER_PASSWORD_LIHAIXIN }}
        repository: ${{ secrets.DOCKER_USERNAME_LIHAIXIN }}/${{ github.event.repository.name }}
        short-description: ${{ github.event.repository.description }}
        readme-filepath: ./README.md
