name: Update Docker Hub README

on:
  push:
    branches: [ master ]
    paths:
      - 'README.md'

jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert README to text
        id: convert-readme
        run: |
          markdown_content=$(cat README.md)
          plain_text=$(echo "$markdown_content" | pandoc -f markdown -t plain)
          echo "::set-output name=description::$plain_text"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME_LIHAIXIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD_LIHAIXIN }}

      - name: Update Docker Hub image description
        env:
          DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_USERNAME_LIHAIXIN }}/${{ github.event.repository.name }}
          DESCRIPTION: ${{ steps.convert-readme.outputs.description }}
        run: |
          echo "${{ env.DESCRIPTION }}" > description.txt
          curl -X PUT -H "Content-Type: application/json" --user "${{ secrets.DOCKER_HUB_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" https://hub.docker.com/v2/repositories/${{ env.DOCKER_HUB_REPO }}/ -d '{"full_description": "'"$(cat description.txt)"'"}'
